// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatWebServer.Models;

namespace ProjekatWebServer.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    [Migration("20210205140841_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ProjekatWebServer.Models.Fabrika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_F")
                        .UseIdentityColumn();

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Fabrika");
                });

            modelBuilder.Entity("ProjekatWebServer.Models.Silos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("FabrikaID")
                        .HasColumnType("int");

                    b.Property<string>("Kapacitet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kapacitet");

                    b.Property<string>("Oznaka")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Oznaka");

                    b.Property<string>("TrenutnaKolicina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrenutnaKolicina");

                    b.HasKey("ID");

                    b.HasIndex("FabrikaID");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("ProjekatWebServer.Models.Silos", b =>
                {
                    b.HasOne("ProjekatWebServer.Models.Fabrika", "Fabrika")
                        .WithMany("silosi")
                        .HasForeignKey("FabrikaID");

                    b.Navigation("Fabrika");
                });

            modelBuilder.Entity("ProjekatWebServer.Models.Fabrika", b =>
                {
                    b.Navigation("silosi");
                });
#pragma warning restore 612, 618
        }
    }
}
